name: Post to Discord

on:
  schedule:
    - cron: '0 9 * * MON' # Every Monday at 09:00 UTC

jobs:
  post-discord:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Discord bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: node index.js